### ISSUE TITLE
Test resources handling in multi-module projects 

### ISSUE THREAD

**Issue by sebkur** [eclipse/buildship#1009]
I have this setup regularly in projects: the project consists of two or more modules and each module has its
own testing code. Naturally each module has a logging configuration in its test resources. When a
module B depends on a module A, then in Eclipse the testing resources from A will also be available on the testing
runtime classpath for B, which is inconsistent with what Gradle does. In the case of some logging framework such as
logback, it detects the situation and complains about the logging configuration being on the classpath multiple times.
I have seen #354 and a number of related issues but I did not find a duplicate of this exactly. I have also set up a minimal
[example project](https://github.com/sebkur/test-gradle-eclipse) that brings up the issue.

### Expected Behavior
The Eclipse project should be configured by buildship to be in line with the Gradle behavior, i.e. test resources from module A should not be available to testing code from module B.

### Current Behavior
I can access resources from `A/src/test/resources` and classes from `A/src/test/java` from `B/src/test/java`.

### Context
The issue occurs naturally when implementing tests for multi-module projects and using a logging configuration for each of them.

### Steps to Reproduce 
Please see the [example project](https://github.com/sebkur/test-gradle-eclipse).

### Your Environment
Gradle 6.5.1
Eclipse 2020-06 (4.16.0).

**Comment by sebkur** [comment]
Also see the branch [wont-compile-with-gradle](https://github.com/sebkur/test-gradle-eclipse/tree/wont-compile-with-gradle) for an extended example that does compile with Eclipse but does not compile using Gradle

**Comment by cristatus** [comment]
Facing same issue...

**Comment by donat** [comment]
This has been fixed in Gradle 6.7: https://github.com/gradle/gradle/issues/12354

**Comment by cristatus** [comment]
> This has been fixed in Gradle 6.7: [gradle/gradle#12354](https://github.com/gradle/gradle/issues/12354)

I am facing this issue with gradle 6.7.1 only.

**Comment by donat** [comment]
> I am facing this issue with gradle 6.7.1 only.
@cristatus I've tested the example project from the original description and it seemed fine with 6.7. Can you please compare that with your case and maybe create an example project displaying the problem?

**Comment by cristatus** [comment]
> > I am facing this issue with gradle 6.7.1 only.
> 
> @cristatus I've tested the example project from the original description and it seemed fine with 6.7. Can you please compare that with your case and maybe create an example project displaying the problem?

@donat I have just tested the example project by upgrading to gradle 6.7.1 with latest stable eclipse. It's still failing...

![s1](https://user-images.githubusercontent.com/282290/106763982-63f62700-665d-11eb-96d7-7154baace84f.png)

**Comment by cristatus** [comment]
@donat it works with gradle 6.8.1 and latest buildship. We'll try to upgrade to gradle 6.8.1. Thanks!
