### ISSUE TITLE
"Cannot run tasks for included builds"

### ISSUE THREAD

**Issue by sc1478** [eclipse/buildship#511]
Buildship is telling me it can't do the included builds.

![image](https://user-images.githubusercontent.com/15382550/27868919-d9205274-6163-11e7-8374-6a0c20766625.png)

Yet, if I go to the command line in the same directory and run `./gradlew clean`, gradle has no trouble doing the job.  I tried refreshing the Gradle project from the Eclipse menu, that did not help

Gradle version 4.0
Buildship version   Buildship: Eclipse Plug-ins for Gradle	2.0.1.v20170302-1039	org.eclipse.buildship.feature.group	Eclipse Buildship

Eclipse tells me no updates are available.

**Comment by donat** [comment]
This is a limitation of Gradle itself, as you can't directly address tasks from the included builds.
Basically, when you execute `gradle foo` on a composite build, then those tasks will be executed from the included builds that produce artifacts required by `foo`. You'll find more information in the [user guide](https://docs.gradle.org/4.0/userguide/composite_builds.html#composite_build_executing_tasks).

**Comment by sc1478** [comment]
This is not a composite build.  It is a straightforward multi-project build.

**Comment by donat** [comment]
Nope, the tasks should be disabled only for included builds. I'll have a look how could you end up in this phase. Could you create a sample project exhibiting the problem so that we can use it for the investigation?

**Comment by oehme** [comment]
This usually happens when a user runs `Add Gradle Nature` on a subproject. Our included build detection currently compares the connectionProjectDir against the root project dir, which fails in this case. 

Our detection could instead use the `GradleBuild` model to determine whether a project is from an included build or not. 

Also, we should really finally add proper root project detection, so we use that as the connectionProjectDir, even when the user selects a subproject when adding the nature.

**Comment by sc1478** [comment]
Also, your reply that "this is a limitation of gradle itself" seems to ignore my initial statement 

> Yet, if I go to the command line in the same directory and run ./gradlew clean, gradle has no trouble doing the job. 

Do you still need a sample from me?  I'm not clear at this point.

**Comment by sc1478** [comment]
Is something needed from me to make progress on this issue?

**Comment by fbazbo** [comment]
I'm seeing the same issue, but it was working fine until I just upgraded from Gradle 3.5 to 4

**Comment by sc1478** [comment]
Yes, it's not an issue when using 3.x gradle wrapper, only with 4.

**Comment by fbazbo** [comment]
Actually, I have one multi-project with 4.0 that works and one that doesn't.  Not obvious what's the difference between them...

**Comment by fbazbo** [comment]
Ended up closing all the projects and deleting from eclipse, then "Import Existing Gradle project" and reopened the root project.  Now they all show green again...

**Comment by sc1478** [comment]
Thanks for that tip.  It does work.

**Comment by kcclaas** [comment]
I still have this error as well. I've tried closing, deleting, and re-importing the projects (both by importing the root, and by importing the sub-projects first), but I still can't run tasks for the subprojects. There are green gear icons next to them (unlike the grey ones in the original screenshot here), but double-clicking them doesn't do anything, and right-clicking them gives the same "Cannot run tasks for included builds". These are standard multi-project builds.

I can run the builds/tasks from the command line, and can create run configurations in eclipse to do the same as a work around for now. If I import the subproject first, I can run tasks for it up until I import a project that depends on it.

**Comment by kcclaas** [comment]
Sure, I'll see if I can come up with something tonight.

**Comment by oehme** [comment]
Thank you, I see what the problem is now - the message is wrong. It should read "Cannot run task selectors in non-standard project layouts". In a flat layout like yours, Gradle cannot find the root project when launched from a subproject. This is why we can't make "task selectors" (run this task here and in all subprojects) work. 

"Project tasks" (run this task only in this subproject) should work though. They are hidden by default, but you can show project tasks by checking the correspdoning option in the drop-down menu of the tasks view.

**Comment by sc1478** [comment]
I wish I could provide you a sample of the original project that caused me to open this issue, but the problem in that case went away upon reimporting it into Eclipse.  I can tell you, though, that my project followed the conventional layout pattern in which subprojects were contained in subdirectories of the project root directory.

**Comment by kcclaas** [comment]
@oehme Oh, cool. Thanks for explaining that, I didn't even realize that menu was there. Everything works for me as you said.

**Comment by donat** [comment]
As the problem with the incorrect error message is fixed in #539 and @sc1478's problem is not reproducible, I'm closing this issue as fixed.

**Comment by oehme** [comment]
The problem that @sc1478 faced is very likely caused by what I pointed out here: https://github.com/eclipse/buildship/issues/511#issuecomment-313139422. So I'd keep this issue open until we have investigated whether this is the case.

**Comment by regrog** [comment]
I'm facing this same problem, I'm in a flat layout and can't run subproject tasks as @oehme said: 

> In a flat layout like yours, Gradle cannot find the root project when launched from a subproject. This is why we can't make "task selectors" (run this task here and in all subprojects) work.

But in each gradle project in eclipse exists a file named `org.eclipse.buildship.core.prefs` (in the `.settings` folder) with the property `connection.project.dir` that describes its root project relative to it (`../myRootProject`).
The same happens in a standard layout with a root folder and all subfolder as projects, the property values is `..`

Maybe this can help enhance this behavior.

Thanks in advance!

**Comment by oehme** [comment]
Finding the root project from Buildship is not the problem. The problem is that Gradle has no syntax for running task selectors in subprojects. Only project tasks work. This has to be enhanced in Gradle first.

**Comment by totszwai** [comment]
This is still happening in the latest version. I had to comment out all the dependency projects on the main project's settings.gradle and build.gradle files. Then delete all projects from eclipse, and all them all back in eclipse... then re-enable the dependency projects on the main project again... 

My project structures are like this:
```
include ':lib-core'
include ':lib-signer'
include ':lib-encoder'

project(':lib-core').projectDir = new File(settingsDir, '../lib-core')
project(':lib-signer').projectDir = new File(settingsDir, '../lib-signer')
project(':lib-encoder').projectDir = new File(settingsDir, '../lib-encoder')
```

**Comment by oehme** [comment]
@totszwai You have a flat project layout, please activate the `Show Project Tasks` option in the tasks view. Task Selectors don't work, for the reasons I outlined above.

**Comment by totszwai** [comment]
Ah crap it automatically greyed out all the tasks again. @oehme where exactly is `Show Project Tasks`? I see no such thing under the `Gradle Tasks` panel, there is nothing on the top right corner of the panel, and nothing when right clicking on the nodes nor anywhere in the panel either... I also checked in Windows > Preferences > Gradle

**Comment by totszwai** [comment]
Never mind, found it, wow...

**Comment by oehme** [comment]
@donat I think we should reconsider what we display in the tasks view. Maybe we could get rid of the "show project tasks" option and instead show project tasks automatically if task selectors aren't available. And if task selectors are available we could add an option to the context menu like "run only in this project". That way users never have to switch an option based on their project layout, but always get the best possible support we can give.

Of course long term we should fix Gradle to support task selectors in non-standard layouts :)

**Comment by kuniss** [comment]
For those who had a similar problem in include builds - Check the file `.setting/org.eclipse.buildship.core.prefs` whether the `connection.project.dir` property is empty.
If not, make it empty. 
In my case the grayed tasks become green again. :smile: 

I my case this (non empty property) happens when turning back from included projects to non-included projects...

@donat @oehme Not sure, whether this may help to solve the issue too. In facts, my issue comes from an out dated `.setting/org.eclipse.buildship.core.prefs` .

**Comment by oehme** [comment]
@kuniss You shouldn't need to manually edit the preference file. Just refreshing the root project should do the trick. Any chance you can reproducibly get back into the broken state?

**Comment by kuniss** [comment]
The question is, what is the root project? I do not have such thing like a parent project in Xtext created projects (I know it from)...
Is a those which does not have other included projects?

**Comment by oehme** [comment]
The root project is the one where your settings.gradle file lives.

**Comment by kuniss** [comment]
I guess you may reproduce easily by checking out projects javapos-contracts, javapos-controls, javapos-config-loader from https://github.com/JavaPOSWorkingGroup.
Initially all projects are not include projects.

However, if you add 
```
disableIDEDependencySubstitution=
```
to your gradle.properties (which enables include nature of the projects, see project's `settings.gradle`), refresh Gradle tasks on javapos-contracts and then removes the line above again, the next refresh of Gradle tasks will make the tasks grey.

**Comment by kuniss** [comment]
.. I have a settings.gradle file on each of the projects as they can be checked out independently and in different sets.
Maybe, this is the issue. However, how to get this running otherwise?

**Comment by kuniss** [comment]
Right, I switch between composite builds and not composite builds. I called it *included builds* as I created them using 
```
	if (file('../javapos-contracts').exists()) 		includeBuild '../javapos-contracts'
``` 
Is *included build* not the right term for that?

**Comment by oehme** [comment]
You said "included projects" earlier, which is why I thought you had this problem in a simple multi-project build.

I think this gives us enough information to reproduce and find a fix, thanks Denis!

**Comment by kuniss** [comment]
As you consider it as an issue :smile:, here is another GUI side effect coming from it, I guess:

Same projects are listed several times. I saw up to 4 equal projects some times.
![grafik](https://user-images.githubusercontent.com/1107971/36495802-c137d3c4-1736-11e8-8814-b1034b0237ed.png)

**Comment by ams-tschoening** [comment]
I have a composite build always and the same problem with multiple included builds showing in "Gradle Task". All my projects live under the same workspace root in Eclipse and none of these projects use any subprojects and only one `build.gradle` and `settings.gradle` located in the project root.

```
Eclipse-Workspace
+---de.am_soft.docbeam.client.api
+---de.am_soft.docbeam.client.impl
+---de.am_soft.docbeam.raw.server
+---de.am_soft.documentbeam
+---de.am_soft.util
```

![clipboard01](https://user-images.githubusercontent.com/6223655/45473923-a9d28d80-b738-11e8-8081-d679dfe3a89c.png)

It's 4 times `.api` and 2 times `.impl`, because `.api` exists as a project itself in Eclipse and is included in 3 other projects. `.impl` exists as a project itself as well and is included in one other project only. If tasks can't be executed on included projects anyway, it might be a good idea to not show them at all.

I still don't understand one thing and would be grateful if you could explain the expected behaviour and what the actual problem is (one more time):

I understand that one can not execute tasks of included builds in a composite build because of Gradle itself. I think this makes even sense to me. So in my example above with 4 times having `.api`, I can't execute tasks for 3 of those because those actually represent entries for some included builds and shouldn't even be visible at all.

What I don't understand is why I can't execute tasks on the 1 `.api` entry that seems to represent the Eclipse project itself, independently of any other `includeBuild` in some other project. In the following screenshot all tasks are disabled instead:

![clipboard02](https://user-images.githubusercontent.com/6223655/45474527-52cdb800-b73a-11e8-85a4-623abc246541.png)

When I'm executing `gradlew clean` at the shell directly in the project folder of my Eclipse `.api`-project, that project is cleaned properly. So there can't be any limitation of Gradle itself from my understanding.

So what is the expected behaviour in such a setup? Should I be able to issue tasks for the 1 `.api` project which, while used in a composite build, is somewhat independent as well? If not, why?

Thanks!

**Comment by oehme** [comment]
There shouldn't be 4 times the same project in the tasks view. Please share a reproducible sample.

**Comment by ams-tschoening** [comment]
Find my reduced examples at the bottom, it seems things depend on project-import-order in Eclipse a bit and it doesn't seem to make a difference if I delete the Eclipse-related files or not.

![clipboard01](https://user-images.githubusercontent.com/6223655/45479882-f40f3b00-b747-11e8-9f65-af00b803b5b3.png)
![clipboard02](https://user-images.githubusercontent.com/6223655/45479883-f4a7d180-b747-11e8-978a-f6a442997f90.png)
![clipboard03](https://user-images.githubusercontent.com/6223655/45479884-f4a7d180-b747-11e8-98fc-678af99a761d.png)

[Plugin-Tests.zip](https://github.com/eclipse/buildship/files/2378599/Plugin-Tests.zip)

What about the statement for composite builds? Should one be able to execute tasks of included builds on those included builds only or not?

I would like to be able to sometimes build individual projects regardless of if they are used in a composite build or not and from my understanding that is exactly the use-case for composite builds.

**Comment by ams-tschoening** [comment]
> There is no way to treat it as standalone, except for removing it from the composite.

Couldn't Buildship provide some GUI or context menu which would let me tell it to simply do what I would otherwise need to do on the shell manually?

It even already knows all the available tasks and could put an entry into the already available context menu for the disabled tasks. It could even simply use the shell if it's not possible otherwise, users would still benefit because they wouldn't need to leave Eclipse manually.

**Comment by andreasbisiach** [comment]
I am experiencing the same problem with composite build and greyed out tasks.
I have imported the same composite build project in Eclipse and IntelliJ and the result is quite different. In Eclipse I cannot run any taks configured in the included builds. In IntelliJ that works fine.
I have noticed that this problem occurs "some time" after the projects have been worked one.
Removing them from the workspace and reloading them does not solve the problem.
Any idea?
See the pictures

![image](https://user-images.githubusercontent.com/18190420/54092452-8bb6b480-438c-11e9-91a5-3da81149dc37.png)

**Comment by andreasbisiach** [comment]
> > Should one be able to execute tasks of included builds on those included builds only or not?
> 
> That's currently not possible, as Gradle provides Buildship no way to address those tasks.
> 
> Note that there is a difference when you jump into the project directory on the command line - in that case you are just building that single build. But when you've imported a composite into Buildship, that included build is _always_ treated as included. There is no way to treat it as standalone, except for removing it from the composite.

Is the above statement still current. I have done a bit of test and it seems hat IntelliJ works perfectly fine with composite builds. In addition, closing included projects in eclipse, seems to trigger exposing the tasks in the included builds. Seems like a bug.
Please see my earlier posts with pictures

**Comment by maciejmiklas** [comment]
@kuniss I'm now Version: 2019-12 (4.14.0) and your solution works fine. Without it this whole composite build is totally useless, because it's not possible to generate facets for included projects.

**Comment by ams-tschoening** [comment]
> Couldn't Buildship provide some GUI or context menu which would let me tell it to simply do what I would otherwise need to do on the shell manually?

In current versions of Eclipse and depending on the distribution chosen, this is easily possible without any additional support from Buildship or plugins by simply using `Show in local terminal` of the context menu of projects.

![Clipboard01](https://user-images.githubusercontent.com/6223655/75354434-3cbfa300-58ad-11ea-9be2-cf5d307e7869.png)

This opens a new view with a shell in which Gradle can be executed as needed without leaving Eclipse.

![Clipboard02](https://user-images.githubusercontent.com/6223655/75354644-9f18a380-58ad-11ea-916e-71084d82b440.png)

If that terminal is not provided by default, it can be installed using [the marketplace](https://marketplace.eclipse.org/content/tm-terminal#group-screenshots) or [some alternatives](https://marketplace.eclipse.org/content/easyshell#group-screenshots) chosen.

**Comment by donat** [comment]
Head-up: Gradle 6.8 will allow task execution in included builds. I'll adjust Buildship to support this feature.

**Comment by donat** [comment]
Gradle 6.8 and Buildship 3.1.5  is released.
