### ISSUE TITLE
compileOnly project dependency broken

### ISSUE THREAD

**Issue by andilem** [eclipse/buildship#939]
Setup: a root project with two subprojects (projectA and projectB). Both subprojects are using the java-library plugin.

projectB has a compileOnly dependency on projectA.

With Gradle < 5.6, everything was working perfectly. I could access classes from projectA in projectB.

Starting with Gradle 5.6.0, this is broken. projectA is no longer listed under "Project and External Dependencies" of projectB.

Compilation from the command line still works, so this is only an Eclipse / Buildship problem.

**Comment by regrog** [comment]
Depending on your project specs, maybe projectB should declare an **implementation** dependency on projectA.
https://docs.gradle.org/current/userguide/java_library_plugin.html

**Comment by andilem** [comment]
98% of our dependencies are api or implementation dependencies, but few need to be compileOnly. I don't want these dependency in the runtimeClasspath which I use to create a RunJar from. I know workarounds, but as I wrote, it *did* work with Gradle 5.5.1 and is broken with >= 5.6.

**Comment by donat** [comment]
It seems like it's a change in Gradle. You can fix it by adjusting the classpath picked up by Buildship:
```
plugins {
    // ...
    id 'eclipse'
}

eclipse {
    classpath {
        plusConfigurations += [ configurations.compileOnly ]
   	}
}
```

**Comment by sorabhsahu** [comment]
> 98% of our dependencies are api or implementation dependencies, but few need to be compileOnly. I don't want these dependency in the runtimeClasspath which I use to create a RunJar from. I know workarounds, but as I wrote, it _did_ work in Eclipse with Gradle 5.5.1 and is broken with >= 5.6.

Hi @andilem , I am facing fame problem, I also don't want use one dependency as CompileOnly, Have you fixed this in your project ? Please share valuable information.

**Comment by sorabhsahu** [comment]
> It seems like it's a change in Gradle. You can fix it by adjusting the classpath picked up by Buildship:
> 
> ```
> plugins {
>     // ...
>     id 'eclipse'
> }
> 
> eclipse {
>     classpath {
>         plusConfigurations += [ configurations.compileOnly ]
>    	}
> }
> ```

Thanks @donat

**Comment by hazemkmammu** [comment]
Shouldn't Buildship add the compileOnly to the eclipse classpath? Isn't the proposed solution a hack?

**Comment by donat** [comment]
[`compileClasspath` extends from `compileOnly`](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management) so that should be all good. I like the proposed solution. I'll discuss the possible implications with the dependency team.

**Comment by donat** [comment]
I'm not in a position to decide what's more correct. By default, Gradle adds the compile and the runtime classpath to `plusConfigurations` and this is what Buildship uses: https://github.com/gradle/gradle/blob/2d0225d7406122d7e345f90607438e2ddd85cc07/subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/EclipsePlugin.java#L253-L254

If someone has a universal solution he/she should propose it for the Gradle project, but I don't think Buildship should do an external fine-tuning of the dependency resolution.

**Comment by tonowie** [comment]
Is there any update on this?

The workaround does not work with Gradle 7. compileOnly configuration is not resolvable and build crashes when I try to add it to plusConfigurations. Also compileClasspath extends from compileOnly and implementation so there is no reason for compileOnly dependencies to be missing in composite builds.

**Comment by ldwqh0** [comment]
@tonowie 
how to do this with kts?

**Comment by donat** [comment]
This is fixed in Gradle 6.8 Can anybody confirm?

**Comment by tonowie** [comment]
> This issue has been fixed in Gradle 6.8 Can anybody confirm?

I had the issue with Gradle 7

**Comment by bluepoke** [comment]
@ldwqh0 

@ldwqh0 
> @tonowie how to do this with kts?

I did the following:
`plugins {
    id("eclipse")
}

eclipse {
    classpath {
    	configurations.compileOnly.get().setCanBeResolved(true)
        plusConfigurations.add( configurations.compileOnly.get() )
   	}
}`

**Comment by yuanjinyong** [comment]
Thanks @bluepoke 

```
        eclipse {
            classpath {
                configurations.compileOnly.canBeResolved = true  // Gradle 7 need this line
                plusConfigurations += [ configurations.compileOnly ]
            }
        }
```

**Comment by moley** [comment]
Hi anyone, 
I tried this latest fix and it seems to me it results in "Unresolved dependencies" when using compileOnly together with version catalogues because the version is not resolved. Can anyone confirm? 

As the issue itself is not fixed, I would suggest to reopen???

**Comment by moley** [comment]
Hi anyone,
I tried this latest fix and it seems to me it results in "Unresolved dependencies" when using compileOnly together with version catalogues because the version is not resolved. Can anyone confirm?

**Comment by Kas-tle** [comment]
Yeah I'm not sure why the issue was closed. This still seems to be an issue in Gradle 7, and I imagine Gradle 8 is no different.

**Comment by parthasaradhie** [comment]
I'm also facing the same issue and this completely blocking me using eclipse or vs core for my hava projects.
Same thing happens for testCompile too

This issue is not fixed at all and closed without any resolution.

**Comment by FanYuan0208** [comment]
I have the same problem using gradle 8.4. 
Is there any solutions?
